In [1]:
import pandas as pd

In [2]:
gender_df = pd.read_csv('gender.csv')
gender_df.update(gender_df['gender'].mask(gender_df['gender'] == 'w', 'f'))
gender_df

     rolleID gender
0          1      m
1          2      m
2          3      m
3          4      m
4          5      m
..       ...    ...
404      618      f
405       79      m
406     1979      f
407      710      m
408       12      m

[409 rows x 2 columns]

In [3]:
speakers = pd.read_csv("../rolle.tsv", sep="\t")
additional_speakers = pd.read_csv("../additional_roles.csv", sep=",")
speakers = pd.concat([speakers, additional_speakers], ignore_index=True).drop_duplicates(subset=['name'], keep='first')
print(len(speakers[speakers.duplicated(subset=['name'], keep=False)]), 'duplicates found')
speakers

0 duplicates found

      rolleID                                name
0           1                 Hitchcock, Erzähler
1           2       Justus Jonas, Erster Detektiv
2           3        Peter Shaw, Zweiter Detektiv
3           4  Bob Andrews, Recherchen und Archiv
4           5        Mr. Fentriss, Schriftsteller
...       ...                                 ...
3464       -1                         Cheerleader
3465       -1                       Frauenstimmen
3468       -1                       Abraham King"
3469       -1                          Jacob King
3470       -1                             Soldat.

[3434 rows x 2 columns]

In [4]:
w_identifier = [
    'mrs ',
    'miss ',
    'ms ',
    'mrs. ',
    'miss. ',
    'ms. ',
    'tante ',
    'lady'
]
w = []

m_identifier = [
    'mister ',
    'mr '
    'mister. ',
    'mr. ',
    'onkel '
]
m = []

for i, row in speakers.iterrows():
    if row['rolleID'] == -1:
        continue  # skip UNKNOWNs

    for ident in w_identifier:
        if row['name'].lower().startswith(ident):
            w.append((row['rolleID'], row['name']))
    
    for ident in m_identifier:
        if row['name'].lower().startswith(ident):
            m.append((row['rolleID'], row['name']))
print(f'found {len(w)} w')
print(f'found {len(m)} m')

found 187 w
found 227 m

In [5]:
w

[(7, 'Mrs. Claudius'),
 (8, 'Miss Waggoner'),
 (13, 'Tante Mathilda'),
 (16, 'Mrs. Flora Gunn'),
 (26, 'Mrs. Boogle'),
 (29, 'Miss Chalmers'),
 (53, 'Mrs. Miller'),
 (66, 'Miss Lydia Green'),
 (91, 'Mrs. Smith'),
 (92, 'Mrs. King'),
 (99, 'Miss Sanchez'),
 (109, 'Mrs. Hammond'),
 (112, 'Miss Larson'),
 (120, 'Mrs. Darnley'),
 (143, 'Mrs. Barton'),
 (145, 'Mrs. Dalton'),
 (156, 'Mrs. Dobson'),
 (173, 'Miss Agawam'),
 (207, 'Mrs. Macomber'),
 (240, 'Mrs. Denicola'),
 (249, 'Mrs. Chumley'),
 (250, 'Mrs. Burroughs'),
 (255, 'Mrs. Barron'),
 (286, 'Mrs. Peabody'),
 (291, 'Mrs. Shaw'),
 (298, 'Miss Melody'),
 (316, 'Mrs. Cross'),
 (347, 'Mrs. Manning'),
 (348, 'Mrs. Andrews'),
 (356, 'Mrs. Westerbrook'),
 (444, 'Mrs. Bloomingdale'),
 (471, 'Mrs. Silverstone'),
 (474, 'Mrs. Hartford'),
 (475, 'Mrs. Green'),
 (498, 'Mrs. Rodriguez'),
 (534, 'Mrs. Lu Kwan'),
 (548, 'Mrs. Madigan'),
 (550, 'Mrs. Lydia Cartier'),
 (562, 'Mrs. Aston'),
 (569, 'Mrs. Petersen'),
 (572, 'Mrs. Dream'),
 (578, 'Mrs. Seven'),
 (623, 'Lady MacWeiden'),
 (633, 'Mrs. Harding, Polizeipsychologin'),
 (655, 'Mrs. Grayson'),
 (662, 'Mrs. Jones'),
 (663, 'Mrs. Shoemaker'),
 (672, 'Miss Lilly'),
 (688, 'Mrs. White'),
 (693, 'Lady Day'),
 (699, 'Mrs. Brighton'),
 (700, 'Mrs. Wheel'),
 (715, 'Mrs. Scott'),
 (726, 'Mrs. Meg Baker'),
 (727, 'Mrs. Wood'),
 (750, 'Mrs. Wilbur'),
 (790, 'Mrs. Willow'),
 (797, "Mrs. O'Rien"),
 (827, 'Mrs. Bancroft'),
 (833, 'Mrs. Ashby'),
 (856, 'Tante Mathilda Jones'),
 (862, 'Mrs. Torrance'),
 (875, 'Miss Lana'),
 (898, 'Mrs. Fox'),
 (914, 'Mrs. Kingsley'),
 (934, 'Mrs. Albright'),
 (947, 'Mrs. Osborne'),
 (950, 'Mrs. Bennett'),
 (979, 'Miss Bennett'),
 (983, 'Mrs. Amelia Sparing'),
 (987, 'Mrs. Featherstone'),
 (1030, 'Miss Darraz'),
 (1049, 'Miss Tomkins'),
 (1126, 'Mrs. Pitkätossu'),
 (1136, 'Mrs. Harkort'),
 (1152, 'Miss Luzzy'),
 (1177, 'Mrs. Maruthers'),
 (1205, 'Mrs. Summer Hopkins'),
 (1213, 'Mrs. Johnson'),
 (1223, 'Mrs. Gardiner'),
 (1234, 'Miss Deborah Cassidy'),
 (1236, 'Miss Trimble'),
 (1244, 'Mrs. Robinson'),
 (1268, 'Mrs. Floyd'),
 (1298, 'Mrs. Kretchmer'),
 (1299, 'Mrs. Espenson'),
 (1300, 'Mrs. Wondratschek'),
 (1301, 'Mrs. Field'),
 (1303, 'Miss Daggett'),
 (1318, 'Mrs. Lydia Candle'),
 (1335, 'Mrs. Dearing'),
 (1337, 'Mrs. Hampton'),
 (1339, 'Mrs. Woodrow'),
 (1356, 'Mrs. Wallace'),
 (1379, 'Mrs. Arvidson'),
 (1384, 'Mrs. Kretschmer'),
 (1446, 'Mrs. Roalstad'),
 (1447, 'Mrs. Fernandez'),
 (1511, 'Mrs. Thompson'),
 (1512, 'Mrs. Kato'),
 (1518, 'Mrs. Crouch'),
 (1562, 'Mrs. Carrington'),
 (1565, 'Mrs. Hawkins'),
 (1574, 'Mrs. Penny'),
 (1605, 'Mrs. Violet Conroy'),
 (1622, 'Mrs. Hilton'),
 (1631, 'Mrs. Watson'),
 (1639, 'Mrs. Lockwood'),
 (1682, 'Mrs. Flagstaff'),
 (1688, 'Mrs. McGee'),
 (1690, 'Mrs. Wells'),
 (1709, 'Mrs. Kooning'),
 (1712, 'Mrs. Stenseth'),
 (1785, 'Mrs. Planter'),
 (1810, 'Mrs. Brankle'),
 (1812, 'Mrs. Seymore-Wrightson'),
 (1819, 'Mrs. Willard'),
 (1867, 'Mrs. Torres'),
 (1872, 'Mrs. Dutton'),
 (1874, 'Mrs. Mobray'),
 (1877, 'Mrs. Carmichael'),
 (1898, 'Mrs. Julia Scott'),
 (1902, 'Mrs. Bronkowitz'),
 (1903, 'Lady'),
 (1915, 'Mrs. Hatchett'),
 (1947, 'Miss Mortimer'),
 (1967, 'Mrs. Kirk'),
 (1986, 'Mrs. Cooper'),
 (1988, 'Mrs. Evans'),
 (1994, 'Mrs. Haynes'),
 (2039, 'Miss Harper'),
 (2043, 'Mrs. Burton'),
 (2080, 'Mrs. Wilmers'),
 (2100, 'Mrs. Almond'),
 (2102, 'Mrs. Doyle'),
 (2112, 'Mrs. Martens'),
 (2114, 'Mrs. Corps'),
 (2123, 'Mrs. Weissbein'),
 (2163, 'Mrs. Alexis'),
 (2187, 'Ms. Fletcher'),
 (2195, 'Mrs. Blomquist'),
 (2220, 'Ms. Robinson'),
 (2224, 'Mrs. Bennet'),
 (2233, 'Mrs. Carfioso'),
 (2262, 'Miss Medusa'),
 (2276, 'Mrs. Winter'),
 (2277, 'Mrs. Edvin'),
 (2279, 'Mrs. Fischer'),
 (2296, 'Mrs. Higgers'),
 (2339, 'Mrs. Lindford'),
 (2360, 'Mrs. Becker'),
 (2376, 'Ms. Miller'),
 (2379, 'Ms. Jordan'),
 (2384, 'Mrs. Clifford'),
 (2460, 'Ms. Blender'),
 (2466, 'Mrs. Vanessa Jacobson'),
 (2468, 'Mrs. Bates'),
 (1234, 'Miss Cassidy'),
 (203, 'Miss Osborne'),
 (286, 'Miss Peabody'),
 (1271, 'Mrs Scott'),
 (1513, 'Mrs. Sullivan'),
 (695, 'Mrs Miller'),
 (495, 'Mrs. Jenkins'),
 (469, 'Ms. Adams'),
 (26, 'Mrs Boogle'),
 (29, 'Ms Chalmers'),
 (712, 'Mrs Carrera'),
 (1456, 'Mrs. Hutchinson'),
 (248, 'Mrs. Radford'),
 (298, 'Ms. Melody'),
 (521, 'Mrs Fiedler'),
 (521, 'Mrs. Fiedler'),
 (1205, 'Mrs Summer'),
 (686, 'Mrs. Hazelwood'),
 (790, 'Mrs Willow'),
 (1163, 'Mrs. McGowan'),
 (1248, 'Mrs. Holbrooke'),
 (1420, 'Mrs. Pembroke'),
 (1435, 'Mrs Breckenridge'),
 (1447, 'Mrs Fernandez'),
 (1785, 'Mrs Planter'),
 (1895, 'Ms Bowman'),
 (1872, 'Miss Dutton'),
 (1857, 'Mrs. Roskin'),
 (663, 'Ms. Shoemaker'),
 (578, 'Mrs. Maggie Seven')]

In [6]:
m

[(5, 'Mr. Fentriss, Schriftsteller'),
 (6, 'Mr. Claudius, Kunsthändler'),
 (10, 'Onkel Ramos'),
 (20, 'Mr. Widner'),
 (23, 'Mr. Prentice'),
 (28, 'Mr. Murphy'),
 (30, 'Mr. Hassel'),
 (33, 'Mr. Carson'),
 (45, 'Mr. Dwiggins'),
 (46, 'Mr. Rhandur'),
 (52, 'Mr. Maximillian'),
 (54, 'Mr. Grant'),
 (60, 'Mr. Shelby'),
 (61, 'Mr. Carter'),
 (73, 'Onkel Titus'),
 (97, 'Mr. Jankins'),
 (98, 'Mr. Harris'),
 (104, 'Mr. Smathers'),
 (105, 'Mr. Jensen'),
 (108, 'Mr. Joe Hammond'),
 (136, 'Mr. Shaw'),
 (142, 'Mr. Norris'),
 (170, 'Mr. Frank'),
 (171, 'Mr. Togati'),
 (215, 'Mr. Thomas'),
 (227, 'Mr. Andrews'),
 (238, 'Mr. Hitfield'),
 (239, 'Mr. Bonestell'),
 (251, 'Mr. Burroughs'),
 (253, 'Mr. Agnier'),
 (254, 'Mr. Barron'),
 (289, 'Mr. Conine'),
 (292, 'Mr. Peck'),
 (300, 'Mr. Jacobs'),
 (302, 'Mr. Temple'),
 (317, 'Mr. Cross'),
 (324, 'Mr. Rossing'),
 (346, 'Mr. Manning'),
 (472, 'Mr. Garfield'),
 (473, 'Mr. Hartford'),
 (479, 'Mr. Bow'),
 (554, 'Mr. Whitehead'),
 (563, 'Mr. Krieger'),
 (571, 'Mr. Brian'),
 (604, 'Mr. Toll'),
 (606, 'Mr. Burt'),
 (616, 'Mr. Evans'),
 (619, 'Mr. Charkov'),
 (628, 'Mr. Peacock, Museumsdirektor'),
 (634, 'Mr. Ambler, Assistent'),
 (636, 'Mr. Laurent, Ladenbesitzer'),
 (637, 'Mr. Stepelton, Ladenbesitzer'),
 (654, 'Mr. Gilbert'),
 (656, 'Mr. Perkins'),
 (668, 'Mr. Quin'),
 (669, 'Mr. Conrad Farnham'),
 (683, 'Mr. Smith'),
 (689, 'Mr. Collins'),
 (691, 'Mr. Martin'),
 (692, 'Mr. Caddy'),
 (705, 'Mr. Schwarz'),
 (706, 'Mr. Olin'),
 (733, 'Mr. Harry Falkner'),
 (748, 'Mr. Zhang'),
 (795, 'Mr. Horowitz'),
 (796, 'Mr. Rothman'),
 (798, 'Mr. Applegate'),
 (843, 'Mr. Hendrik'),
 (846, 'Mr. X'),
 (857, 'Mr. Overlook'),
 (861, 'Mr. Torrance'),
 (867, 'Onkel Titus Jones'),
 (868, 'Mr. Walker'),
 (909, 'Mr. Campbell'),
 (913, 'Mr. Kingsley'),
 (922, "Mr. O'Sullivan"),
 (931, 'Mr. Myers'),
 (937, 'Mr. Baker'),
 (941, 'Mr. Monroe'),
 (948, 'Mr. Pentecost'),
 (969, 'Mr. Grogan'),
 (984, 'Mr. Sparing'),
 (996, 'Mr. Bambridge'),
 (1016, 'Mr. Jackmore'),
 (1042, 'Mr. Settler'),
 (1050, 'Mr. Foley'),
 (1073, 'Mr. Raynes'),
 (1094, 'Mr. Peastone'),
 (1137, 'Mr. Prescott'),
 (1173, 'Mr. Sapchevsky'),
 (1187, 'Mr. Raffer'),
 (1190, 'Mr. Castro'),
 (1207, 'Mr. Elroy Follister'),
 (1231, 'Mr. Grey'),
 (1235, 'Mr. Burke'),
 (1237, 'Mr. Weston'),
 (1262, 'Mr. Vancura'),
 (1264, 'Mr. Mosley'),
 (1272, 'Mr. Darrow'),
 (1331, 'Mr. Louis'),
 (1334, 'Mr. Bennet'),
 (1343, 'Mr. Clark'),
 (1345, 'Mr. Callister'),
 (1378, 'Mr. Arvidson'),
 (1426, 'Mr. Lloyd'),
 (1504, 'Mr. Tilton'),
 (1505, 'Mr. Walsh'),
 (1536, 'Mr. Nostigan'),
 (1561, 'Mr. Carrington'),
 (1564, 'Mr. Hawkins'),
 (1569, 'Mr. Sisko'),
 (1576, 'Mr. Hooper'),
 (1578, 'Mr. Turner'),
 (1581, 'Mr. Gabriel Paredes'),
 (1606, 'Mr. Alex Scott'),
 (1623, 'Mr. Warren'),
 (1636, 'Mr. Whitty'),
 (1638, 'Mr. Arbuthnott'),
 (1643, 'Mr. McBrandon'),
 (1738, 'Mr. Aaron Grover'),
 (1743, 'Mr. Rubberwood'),
 (1744, 'Mr. Parker Mayfield'),
 (1748, 'Mr. August'),
 (1751, 'Mr. Anderson'),
 (1754, 'Mr. Randur'),
 (1775, 'Mr. Friedman'),
 (1778, 'Mr. Miller'),
 (1800, 'Mr. Pinches'),
 (1809, 'Mr. Mason Huntington'),
 (1828, 'Mr. Allister Frain'),
 (1878, 'Mr. Jeremiah Carmichael'),
 (1914, 'Mr. Puckle'),
 (1980, 'Mr. Rice'),
 (1987, 'Mr. Bumblebee'),
 (1989, 'Mr. Powers'),
 (1995, 'Mr. Haynes'),
 (2077, 'Mr. Hillmond'),
 (2099, 'Mr. Laslokow'),
 (2101, 'Mr. Doyle'),
 (2113, 'Mr. Corps'),
 (2115, 'Mr. Doodles'),
 (2119, 'Mr. Pim'),
 (2124, 'Mr. Blacktree'),
 (2127, 'Mr. Trader'),
 (2136, 'Mr. Jenkins'),
 (2143, 'Mr. Kay'),
 (2144, 'Mr. Karst'),
 (2183, 'Mr. Blazar'),
 (2191, 'Mr. Heines'),
 (2196, 'Mr. Tabbs'),
 (2225, 'Mr. Reed'),
 (2226, 'Mr. Osborn'),
 (2275, 'Mr. Moses'),
 (2278, 'Mr. Stone'),
 (2295, 'Mr. Pinkert'),
 (2298, 'Mr. Borgs'),
 (2321, 'Mr. Lane'),
 (2322, 'Mr. Kent'),
 (2327, 'Mr. Conolly'),
 (2333, 'Mr. Flynt'),
 (2348, 'Mr. Schenker'),
 (2361, 'Mr. Hiller'),
 (2362, 'Mr. Benson'),
 (2364, 'Mr. Loew'),
 (2369, 'Mr. Think'),
 (2401, 'Mr. Zimmerman'),
 (2440, 'Mr. Watts'),
 (2457, 'Mr. Connolly'),
 (2467, 'Mr. Daniel Jacobson'),
 (309, 'Mr. Brewster'),
 (228, 'Mr. Crowe'),
 (230, 'Mr. MacGruder'),
 (231, 'Mr. Hanley'),
 (1085, 'Mr. Woodland'),
 (1087, 'Mr. Wellford'),
 (1179, 'Mr. Taylor'),
 (137, 'Mr. Denton'),
 (138, 'Mr. Farraday'),
 (281, 'Mr. Donner'),
 (280, 'Mr. Slater'),
 (144, 'Mr. Dalton'),
 (208, 'Mr. Atkinson'),
 (287, 'Mr. Burton'),
 (405, 'Mr. Torres'),
 (404, 'Mr. Gilbar'),
 (411, 'Mr. Firestone'),
 (422, 'Mr. Norman'),
 (951, 'Mr. Crowle'),
 (956, 'Mr. Abazza'),
 (1170, 'Mr. Davis'),
 (1257, 'Mr. Hunnicutt'),
 (1261, 'Mr. Gizmo'),
 (1260, 'Mr. Chester'),
 (1295, 'Mr. Greenwalt'),
 (1297, 'Mr. Deforge'),
 (412, 'Mr. Crocker'),
 (907, 'Mr. Thorndike'),
 (330, 'Mr. Sears'),
 (1870, 'Mr. Fairfax'),
 (1372, 'Mr. Tillerman'),
 (1079, 'Mr. Norsworthy'),
 (7, 'Mr. Claudius'),
 (167, 'Mr. Kastner'),
 (213, 'Mr. Gray'),
 (916, 'Mr. Long'),
 (252, 'Mr. Malz'),
 (2171, 'Mr. Wolfe'),
 (293, 'Mr. Snabel'),
 (349, 'Mr. Burnside'),
 (373, 'Mr. Griswold'),
 (381, 'Mr. Morningbaum'),
 (427, 'Mr. Ek'),
 (498, 'Mr. Rodriguez'),
 (1130, 'Mr. Waterfield'),
 (1248, 'Mr. Holbrooke'),
 (1310, 'Mr. Sesto'),
 (1305, 'Mr. Tornby'),
 (1597, 'Mr. Lewis'),
 (1421, 'Mr. Vaughn'),
 (1425, 'Mr. Cray'),
 (906, 'Mr. Boyd'),
 (953, 'Mr. Taper'),
 (1472, 'Mr. Faring'),
 (1574, 'Mr. Penny'),
 (417, 'Mr. Duggan'),
 (661, 'Mr. Truman'),
 (1093, 'Mr. Sinclair')]

In [7]:
m_df = pd.DataFrame({
    'rolleID': [entry[0] for entry in m],
    'gender': ['m' for _ in range(len(m))]
})
m_df

     rolleID gender
0          5      m
1          6      m
2         10      m
3         20      m
4         23      m
..       ...    ...
222     1472      m
223     1574      m
224      417      m
225      661      m
226     1093      m

[227 rows x 2 columns]

In [8]:
w_df = pd.DataFrame({
    'rolleID': [entry[0] for entry in w],
    'gender': ['w' for _ in range(len(w))]
})
w_df

     rolleID gender
0          7      w
1          8      w
2         13      w
3         16      w
4         26      w
..       ...    ...
182     1895      w
183     1872      w
184     1857      w
185      663      w
186      578      w

[187 rows x 2 columns]

In [9]:
new_gender_df = pd.concat([gender_df, m_df, w_df], ignore_index=True).drop_duplicates(subset=['rolleID'], keep='first')
new_gender_df = new_gender_df.sort_values(by='rolleID')
new_gender_df

     rolleID gender
0          1      m
1          2      m
2          3      m
3          4      m
4          5      m
..       ...    ...
396     2457      m
397     2460      f
398     2466      f
399     2467      m
400     2468      f

[409 rows x 2 columns]

In [10]:
new_gender_df.to_csv('gender.csv',index=False)